kafka:
  bootstrap:
    servers: "localhost:9092"
  producer:
    topic: testKafka
  consumer:
    topic: testKafka
    group:
      id:
        config: test-consumer-group
    polling:
      delay: 100
    max:
      poll:
        interval: 30000
    session:
      timeout: 50000

